### ISSUE TITLE
Old School Bond not unlocked in GE (tradeable)

### ISSUE THREAD

**Issue by ronaldwpope** [CodePanter/another-bronzeman-mode#17] opened 2024-05-01 00:45 UTC
The tradable Old School Bond is locked on the GE. You cannot buy a bond there without first disabling the plugin. The tradeable version of the old school bond should be unlocked since you cannot obtain it in game without first having an untradeable version in your inventory and spending gp to make it tradeable (which you cannot do because the tradeable bond is locked on the GE) . I think the untradeable  bond is unlocked on starting a new account but that doesn't do any good because you cannot by an untradeable bond.

**Comment by ronaldwpope** [comment] 2024-05-01 06:34
It looks like the old school bond should be unlocked by default on line 677 of AnotherBronzemanModePlugin.java :
    queueItemUnlock(ItemID.OLD_SCHOOL_BOND);
But it doesn't work. Maybe use ItemID.OLD_SCHOOL_BOND_UNTRADEABLE ? Perhaps the 2 IDs got transposed?

**Comment by CodePanter** [comment] 2024-05-02 10:46
Aah interesting! I will try to take a look this weekend, thank you for bringing this to my attention!

**Comment by CodePanter** [comment] 2024-11-25 13:27
Closing this due to being unable to reproduce it, and no one else reporting it as an issue.

**Closed by CodePanter** 2024-11-25 13:27 UTC
