### ISSUE TITLE
chat message on unlock not working

### ISSUE THREAD

**Issue by Rowey79** [CodePanter/another-bronzeman-mode#14] opened 2023-04-25 16:45 UTC
hi mate, enjoying the feature! chat message on unlock doesn't seem to work for me?

thanks!

**Comment by Rowey79** [comment] 2023-05-10 23:48
Sorry I missed this, any luck? still doesn't seem to work

**Comment by CodePanter** [comment] 2024-11-25 13:25
Closing this due to being unable to reproduce it, and no one else reporting it as an issue.

**Closed by CodePanter** 2024-11-25 13:25 UTC
